name: GitHub Actions Demo
run-name: ${{github.actor}} is testing out GitHub Actions
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Primeiro STEP do fluxo
              run: echo "The job was automatically triggered by a ${{github.event_name}} event."
            - name: Segundo STEP do fluxo
              run: echo "14/09/2026."
            - name: Terceiro STEP do fluxo
              run: echo "A execução do fluxo foi concluída com sucesso na data 14/09/2026."